In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('Iris.csv')
df

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [4]:
df.columns = ['0', '1', '2', '3', '4']
df

       0    1    2    3               4
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [7]:
df['4'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [10]:
setosa = df[df['4'] == 'Iris-setosa']
setosa

      0    1    2    3            4
0   4.9  3.0  1.4  0.2  Iris-setosa
1   4.7  3.2  1.3  0.2  Iris-setosa
2   4.6  3.1  1.5  0.2  Iris-setosa
3   5.0  3.6  1.4  0.2  Iris-setosa
4   5.4  3.9  1.7  0.4  Iris-setosa
5   4.6  3.4  1.4  0.3  Iris-setosa
6   5.0  3.4  1.5  0.2  Iris-setosa
7   4.4  2.9  1.4  0.2  Iris-setosa
8   4.9  3.1  1.5  0.1  Iris-setosa
9   5.4  3.7  1.5  0.2  Iris-setosa
10  4.8  3.4  1.6  0.2  Iris-setosa
11  4.8  3.0  1.4  0.1  Iris-setosa
12  4.3  3.0  1.1  0.1  Iris-setosa
13  5.8  4.0  1.2  0.2  Iris-setosa
14  5.7  4.4  1.5  0.4  Iris-setosa
15  5.4  3.9  1.3  0.4  Iris-setosa
16  5.1  3.5  1.4  0.3  Iris-setosa
17  5.7  3.8  1.7  0.3  Iris-setosa
18  5.1  3.8  1.5  0.3  Iris-setosa
19  5.4  3.4  1.7  0.2  Iris-setosa
20  5.1  3.7  1.5  0.4  Iris-setosa
21  4.6  3.6  1.0  0.2  Iris-setosa
22  5.1  3.3  1.7  0.5  Iris-setosa
23  4.8  3.4  1.9  0.2  Iris-setosa
24  5.0  3.0  1.6  0.2  Iris-setosa
25  5.0  3.4  1.6  0.4  Iris-setosa
26  5.2  3.5  1.5  0.2  Iris-setosa
27  5.2  3.4  1.4  0.2  Iris-setosa
28  4.7  3.2  1.6  0.2  Iris-setosa
29  4.8  3.1  1.6  0.2  Iris-setosa
30  5.4  3.4  1.5  0.4  Iris-setosa
31  5.2  4.1  1.5  0.1  Iris-setosa
32  5.5  4.2  1.4  0.2  Iris-setosa
33  4.9  3.1  1.5  0.1  Iris-setosa
34  5.0  3.2  1.2  0.2  Iris-setosa
35  5.5  3.5  1.3  0.2  Iris-setosa
36  4.9  3.1  1.5  0.1  Iris-setosa
37  4.4  3.0  1.3  0.2  Iris-setosa
38  5.1  3.4  1.5  0.2  Iris-setosa
39  5.0  3.5  1.3  0.3  Iris-setosa
40  4.5  2.3  1.3  0.3  Iris-setosa
41  4.4  3.2  1.3  0.2  Iris-setosa
42  5.0  3.5  1.6  0.6  Iris-setosa
43  5.1  3.8  1.9  0.4  Iris-setosa
44  4.8  3.0  1.4  0.3  Iris-setosa
45  5.1  3.8  1.6  0.2  Iris-setosa
46  4.6  3.2  1.4  0.2  Iris-setosa
47  5.3  3.7  1.5  0.2  Iris-setosa
48  5.0  3.3  1.4  0.2  Iris-setosa

In [11]:
versicolor = df[df['4'] == 'Iris-versicolor']
versicolor

      0    1    2    3                4
49  7.0  3.2  4.7  1.4  Iris-versicolor
50  6.4  3.2  4.5  1.5  Iris-versicolor
51  6.9  3.1  4.9  1.5  Iris-versicolor
52  5.5  2.3  4.0  1.3  Iris-versicolor
53  6.5  2.8  4.6  1.5  Iris-versicolor
54  5.7  2.8  4.5  1.3  Iris-versicolor
55  6.3  3.3  4.7  1.6  Iris-versicolor
56  4.9  2.4  3.3  1.0  Iris-versicolor
57  6.6  2.9  4.6  1.3  Iris-versicolor
58  5.2  2.7  3.9  1.4  Iris-versicolor
59  5.0  2.0  3.5  1.0  Iris-versicolor
60  5.9  3.0  4.2  1.5  Iris-versicolor
61  6.0  2.2  4.0  1.0  Iris-versicolor
62  6.1  2.9  4.7  1.4  Iris-versicolor
63  5.6  2.9  3.6  1.3  Iris-versicolor
64  6.7  3.1  4.4  1.4  Iris-versicolor
65  5.6  3.0  4.5  1.5  Iris-versicolor
66  5.8  2.7  4.1  1.0  Iris-versicolor
67  6.2  2.2  4.5  1.5  Iris-versicolor
68  5.6  2.5  3.9  1.1  Iris-versicolor
69  5.9  3.2  4.8  1.8  Iris-versicolor
70  6.1  2.8  4.0  1.3  Iris-versicolor
71  6.3  2.5  4.9  1.5  Iris-versicolor
72  6.1  2.8  4.7  1.2  Iris-versicolor
73  6.4  2.9  4.3  1.3  Iris-versicolor
74  6.6  3.0  4.4  1.4  Iris-versicolor
75  6.8  2.8  4.8  1.4  Iris-versicolor
76  6.7  3.0  5.0  1.7  Iris-versicolor
77  6.0  2.9  4.5  1.5  Iris-versicolor
78  5.7  2.6  3.5  1.0  Iris-versicolor
79  5.5  2.4  3.8  1.1  Iris-versicolor
80  5.5  2.4  3.7  1.0  Iris-versicolor
81  5.8  2.7  3.9  1.2  Iris-versicolor
82  6.0  2.7  5.1  1.6  Iris-versicolor
83  5.4  3.0  4.5  1.5  Iris-versicolor
84  6.0  3.4  4.5  1.6  Iris-versicolor
85  6.7  3.1  4.7  1.5  Iris-versicolor
86  6.3  2.3  4.4  1.3  Iris-versicolor
87  5.6  3.0  4.1  1.3  Iris-versicolor
88  5.5  2.5  4.0  1.3  Iris-versicolor
89  5.5  2.6  4.4  1.2  Iris-versicolor
90  6.1  3.0  4.6  1.4  Iris-versicolor
91  5.8  2.6  4.0  1.2  Iris-versicolor
92  5.0  2.3  3.3  1.0  Iris-versicolor
93  5.6  2.7  4.2  1.3  Iris-versicolor
94  5.7  3.0  4.2  1.2  Iris-versicolor
95  5.7  2.9  4.2  1.3  Iris-versicolor
96  6.2  2.9  4.3  1.3  Iris-versicolor
97  5.1  2.5  3.0  1.1  Iris-versicolor
98  5.7  2.8  4.1  1.3  Iris-versicolor

In [12]:
merge = pd.concat([versicolor, setosa])
merge

      0    1    2    3                4
49  7.0  3.2  4.7  1.4  Iris-versicolor
50  6.4  3.2  4.5  1.5  Iris-versicolor
51  6.9  3.1  4.9  1.5  Iris-versicolor
52  5.5  2.3  4.0  1.3  Iris-versicolor
53  6.5  2.8  4.6  1.5  Iris-versicolor
..  ...  ...  ...  ...              ...
44  4.8  3.0  1.4  0.3      Iris-setosa
45  5.1  3.8  1.6  0.2      Iris-setosa
46  4.6  3.2  1.4  0.2      Iris-setosa
47  5.3  3.7  1.5  0.2      Iris-setosa
48  5.0  3.3  1.4  0.2      Iris-setosa

[99 rows x 5 columns]

In [14]:
sort = df.sort_values('0', ascending=False)
sort

       0    1    2    3               4
130  7.9  3.8  6.4  2.0  Iris-virginica
134  7.7  3.0  6.1  2.3  Iris-virginica
121  7.7  2.8  6.7  2.0  Iris-virginica
116  7.7  3.8  6.7  2.2  Iris-virginica
117  7.7  2.6  6.9  2.3  Iris-virginica
..   ...  ...  ...  ...             ...
40   4.5  2.3  1.3  0.3     Iris-setosa
7    4.4  2.9  1.4  0.2     Iris-setosa
41   4.4  3.2  1.3  0.2     Iris-setosa
37   4.4  3.0  1.3  0.2     Iris-setosa
12   4.3  3.0  1.1  0.1     Iris-setosa

[149 rows x 5 columns]

In [15]:
trans = df.T
trans

,0,1,2,3,4,5,6,7,8,9,...,139,140,141,142,143,144,145,146,147,148
0,4.9,4.7,4.6,5.0,5.4,4.6,5.0,4.4,4.9,5.4,...,6.7,6.9,5.8,6.8,6.7,6.7,6.3,6.5,6.2,5.9
1,3.0,3.2,3.1,3.6,3.9,3.4,3.4,2.9,3.1,3.7,...,3.1,3.1,2.7,3.2,3.3,3.0,2.5,3.0,3.4,3.0
2,1.4,1.3,1.5,1.4,1.7,1.4,1.5,1.4,1.5,1.5,...,5.6,5.1,5.1,5.9,5.7,5.2,5.0,5.2,5.4,5.1
3,0.2,0.2,0.2,0.2,0.4,0.3,0.2,0.2,0.1,0.2,...,2.4,2.3,1.9,2.3,2.5,2.3,1.9,2.0,2.3,1.8
4,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,...,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica

In [23]:
melt = pd.melt(df, id_vars=['0','1','2', '4'])
melt

       0    1    2               4 variable  value
0    4.9  3.0  1.4     Iris-setosa        3    0.2
1    4.7  3.2  1.3     Iris-setosa        3    0.2
2    4.6  3.1  1.5     Iris-setosa        3    0.2
3    5.0  3.6  1.4     Iris-setosa        3    0.2
4    5.4  3.9  1.7     Iris-setosa        3    0.4
..   ...  ...  ...             ...      ...    ...
144  6.7  3.0  5.2  Iris-virginica        3    2.3
145  6.3  2.5  5.0  Iris-virginica        3    1.9
146  6.5  3.0  5.2  Iris-virginica        3    2.0
147  6.2  3.4  5.4  Iris-virginica        3    2.3
148  5.9  3.0  5.1  Iris-virginica        3    1.8

[149 rows x 6 columns]

In [24]:
pt = pd.pivot_table(df, index=['4'])
pt

                        0         1         2         3
4
Iris-setosa      5.004082  3.416327  1.465306  0.244898
Iris-versicolor  5.936000  2.770000  4.260000  1.326000
Iris-virginica   6.588000  2.974000  5.552000  2.026000